### ISSUE TITLE
有什么开发计划吗

### ISSUE THREAD

**Issue by pusidun** [mallorgan/LMall#1]
比如TODO list

**Comment by wanghengGit** [comment]
这周先熟悉我们要参考的项目。之后分模块开始开发

**Comment by wanghengGit** [comment]
模块分好之后会提交一份todo list,我们这边有个微信群交流，大家都加里面，方便讨论

**Comment by pusidun** [comment]
@wanghengGit 
README写的是qq群啊

**Comment by wanghengGit** [comment]
微信群很麻烦，二维码七天过期，方便先加我微信jsvscode,拉进群
